FacultateSite2/FacultateSite2/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('situatie_scolara/', include('situatie_scolara.urls', namespace='situatie_scolara')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

FacultateSite2/accounts/urls.py
from django.urls import path, reverse_lazy, re_path, include
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup_professor', views.profesor_view,name='signup_professor'),
    path('signup_student', views.student_view,name='signup_student'),
    #path('login', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('login/', views.user_login ,name='login'),
    path('logout/',views.user_logout ,name='logout'),
    path('sign_up/',views.SignUp.as_view(),name='sign_up'),
    re_path('date_personale_student/(?P<pk>\d+)/(?P<name>\w+)/$',views.DatePersonaleStudentView.as_view(),name='date_personale_student'),
    re_path('date_personale_profesor/(?P<pk>\d+)/(?P<name>\w+)/$',views.DatePersonaleProfesorView.as_view(),name='date_personale_profesor'),
]

FacultateSite2/orar/urls.py
from . import views
from django.urls import path, include
app_name = 'orar'

urlpatterns = [
    path('creare_orar/',views.CreareOrarView,name='creare_orar'),
    # path('adaugare_note/',views.adaugare_note,name='adaugare_note'),
    # path('selectie_materii/',views.SelectieMateriiView,name='selectie_materii'),
    # path('creare_grupe/',views.CreareGrupeView,name='creare_grupe')
]

FacultateSite2/situatie_scolara/urls.py
from django.urls import path, reverse_lazy, re_path, include
from django.contrib.auth import views as auth_views
from . import views


app_name = 'situatie_scolara'

urlpatterns = [
    path('vizualizare_situatie_scolara/',views.vizualizare_situatie_scolara,name='vizualizare_situatie_scolara'),
    path('adaugare_note/',views.adaugare_note,name='adaugare_note'),
    path('selectie_materii/',views.SelectieMateriiView,name='selectie_materii'),
    path('creare_grupe/',views.CreareGrupeView,name='creare_grupe')
]

FacultateSite2/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <title>Facultate</title>
  </head>
  <body>
    <nav class="navbar navbar-inverse" role="navigation" id='navbar'>
      <div class="container-fluid">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Facultatea de Inginerie Software</a>
        <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
            {% if request.user.is_student %}
              <li> <h1>Student</h1> </li>
              <li> <a href="{% url 'accounts:date_personale_student' pk=request.user.student.pk name=request.user.username %}">Date personale</a> </li>
              <li> <a href="{% url 'situatie_scolara:vizualizare_situatie_scolara' %}">Situatie Scolara</a> </li>
            {% else %}
              <li> <a href="{% url 'situatie_scolara:adaugare_note' %}">Adaugare Note</a> </li>
              <li> <a href="{% url 'accounts:date_personale_profesor' pk=request.user.profesor.pk name=request.user.username %}">Date personale</a> </li>
            {% endif %}
            {% if user.is_superuser %}
            <li> <a href="{% url 'situatie_scolara:creare_grupe' %}">Creare grupe</a> </li>
            {% endif %}
            <li> <a href="{% url 'accounts:logout' %}">Log Out</a> </li>
          {% else %}
            <li> <a href="{% url 'accounts:login' %}">Autentificare</a> </li>
            <li> <a href="{% url 'accounts:signup_student' %}">Inregistrare student</a> </li>
            <li> <a href="{% url 'accounts:signup_professor' %}">Inregistrare profesor</a> </li>

          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container-fluid mycontent">
      {% block content %}
      {% endblock  %}
    </div>

  </body>
</html>

FacultateSite2/templates/index.html
{% extends "base.html" %}
{% block content %}
  <h1>Bine ati venit pe site-ul Facultatii de Inginerie Software</h1>
  
{% endblock content %}